Shop/ViewModels/CarsListViewModel.cs
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class CarsListViewModel
    {
        public IEnumerable<Car> AllCars { get; set; }
        public string currentCategory { get; set; }
    }
}

Shop/ViewModels/HomeViewModel.cs
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Car> favCars { get; set; }
    }
}

Shop/ViewModels/ShopCartViewModel.cs
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart shopCart { get; set; }
    }
}

Shop/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.ViewModels;

namespace Shop.Controllers
{
    public class CarsController : Controller
    {


        private readonly IAllCars _allCars;
        private readonly ICarsCategory _allCategories;
        public CarsController(IAllCars allCars, ICarsCategory carsCategory)
        {
            _allCars = allCars;
            _allCategories = carsCategory;
        }

        public string Index()
        {
            return "dsdsdsdsd";
        }

        [Route("Cars/List")]
        [Route("Cars/List/{category}")]
        public IActionResult List(string category)
        {
            IEnumerable<Car> cars = null;
            string currentCategory = "";
            if (string.IsNullOrEmpty(category))
            {
                cars = _allCars.Cars.OrderBy(item => item.id);
            }
            else
            {
                if (string.Equals("electro", category, StringComparison.OrdinalIgnoreCase))
                {
                    cars = _allCars.Cars.Where(iteem => iteem.Category.categoryName.Equals("electric"))
                        .OrderBy(item => item.id);
                    currentCategory = "Classic cars";

                }
                else if (string.Equals("fuel", category, StringComparison.OrdinalIgnoreCase))
                {
                    cars = _allCars.Cars.Where(iteem => iteem.Category.categoryName.Equals("classic"))
                        .OrderBy(item => item.id);
                    currentCategory = "Electric cars";
                }
                else
                {
                    cars = _allCars.Cars.OrderBy(item => item.id);
                }
            }
            var carObj = new CarsListViewModel()
            {
                AllCars = cars,
                currentCategory = currentCategory

            };
            ViewBag.Title = "Page with automobile";
            return View(carObj);
        }
    }
}

Shop/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.ViewModels;

namespace Shop.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAllCars _carRep;
        public HomeController(IAllCars carRepository)
        {
            _carRep = carRepository;
        }
        public IActionResult Index()
        {
            var homeCars = new HomeViewModel()
            {
                favCars = _carRep.GetFavCars
            };

            return View(homeCars);
        }
    }
}

Shop/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;

namespace Shop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrders orders;
        private readonly ShopCart shopCart;

        public OrderController(IOrders orders, ShopCart shopCart)
        {
            this.orders = orders;
            this.shopCart = shopCart;
        }
        public IActionResult CheckOut()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CheckOut(Order order)
        {
            shopCart.listShopItems = shopCart.GetShopItems();
            if (shopCart.listShopItems.Count == 0)
            {
                ModelState.AddModelError("", "You must have items");
            }
            if (ModelState.IsValid)
            {
                orders.CreaateOrder(order);
                return RedirectToAction("Complete");
            }
            return View(order);
        }
        public IActionResult Complete()
        {
            ViewBag.Message = "Order processed successfully";
            return View();
        }
    }
}

Shop/Controllers/ShopCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.Data.Repository;
using Shop.ViewModels;

namespace Shop.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IAllCars _carRep;
        private readonly ShopCart _shopCart;
        public ShopCartController(IAllCars carRepository,ShopCart shopCart)
        {
            _carRep = carRepository;
            _shopCart = shopCart;
        }
        public IActionResult Index()
        {
            var items = _shopCart.GetShopItems();
            _shopCart.listShopItems = items;
            var obj = new ShopCartViewModel() { shopCart = _shopCart };
            return View(obj);
        }
        public RedirectToActionResult AddToCart(int id)
        {
            var item = _carRep.Cars.FirstOrDefault(i => i.id == id);
            if (item!=null)
            {
                _shopCart.AddToCArt(item);
            }
            return RedirectToAction("Index");
        }
    }
}

Shop/Views/Cars/List.cshtml
@*@using Shop.ViewModels
@model CarsListViewModel*@


<h1>All Cars</h1>
<h3>@Model.currentCategory</h3>
<div class="row justify-content-md-center mt-5 mb-2 ">
        @{
            foreach (Car car in Model.AllCars)
            {
                @await Html.PartialAsync("AllCars", car)
            }
        }
</div>

Shop/Views/Home/Index.cshtml
@model HomeViewModel

<h1>Best Cars</h1>
<div class="row justify-content-md-center mt-5 mb-2 ">
    @{
        foreach (Car car in Model.favCars)
        {
            @await Html.PartialAsync("AllCars", car)
        }
    }
</div>

Shop/Views/Order/CheckOut.cshtml
@model Order
<h3>Ordering</h3>
<div class="row mb-5">
    <form asp-action="CheckOut" method="post" class="form-horizontal">
        <div class="form-group">
            <label asp-for="name"></label>
            <div class="col-12">
                <input class="form-control" asp-for="name" />
                <span class="text-danger" asp-validation-for="name"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="surname"></label>
            <div class="col-12">
                <input class="form-control" asp-for="surname" />
                <span class="text-danger" asp-validation-for="surname"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="adress"></label>
            <div class="col-12">
                <input class="form-control" asp-for="adress" />
                <span class="text-danger" asp-validation-for="adress"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="phone"></label>
            <div class="col-12">
                <input class="form-control" asp-for="phone" />
                <span class="text-danger" asp-validation-for="phone"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="email"></label>
            <div class="col-12">
                <input class="form-control" asp-for="email" />
                <span class="text-danger" asp-validation-for="email"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-12">
                <input class="btn btn-success" type="submit" value="Successed Ordering" />
            </div>
        </div>
    </form>
</div>

Shop/Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

Shop/Views/Shared/AllCars.cshtml
@model Car
<div class="col col-lg-4">
    <img src="@Model.img" class="img-thumbnail" alt="@Model.name" />
    <h2>Model: @Model.name</h2>
    <p>@Model.shortDesc</p>
    <p>Price: @Model.price.ToString("c")</p>
    <p><a class="btn btn-warning" asp-controller="ShopCart"  asp-action="AddToCart" asp-route-id="@Model.id">Add to Cart</a></p>
</div>

Shop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/style.css" type="text/css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <a class="navbar-brand" href="#">itProger</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Cars" asp-action="List">Cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Cars" asp-action="List" asp-route-category="electro">Electric cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Cars" asp-action="List" asp-route-category="fuel">Classic cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " href="/ShopCart/">Basket</a>
                    </li>
                </ul>
                <form class="form-inline mt-2 mt-md-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        @RenderBody()
    </div>
    @*<script  src="~/js/bootstrap.min.js" type="text/javascript"></script>*@
    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>© @DateTime.Now.Year All rights reserved · <a href="#">Agreement</a></p>
    </footer>
</body>
</html>

Shop/Views/ShopCart/Index.cshtml
@model ShopCartViewModel
<div class="container">
    @foreach (var item in Model.shopCart.listShopItems)
    {
        <div class="alert alert-warning mt-3">
            <b>Car:</b>@item.car.name<br />
            <b>Price:</b>@item.price.ToString("C");
        </div>
    }
    <hr />
    <a class="btn btn-danger" asp-controller ="Order" asp-action ="CheckOut">Pay</a>
</div>